### ISSUE TITLE
Add primary key to the casbin table

### ISSUE THREAD

**Issue by jonaskello** [touchifyapp/casbin-pg-adapter#1]
Thanks for making this adapter. I was trying it out and found that there is no primary key defined on the casbin table. Tools like dBeaver requires a primary key to delete a single row. Could it be added?

**Comment by SomaticIT** [comment]
Hi,

Thank you for trying this module.
You are totally right, it miss the primary key!

We will fix it in next release (next week).
We will also add a unique constraint on values to avoid duplicate entries.

I will let you know when next release is published

**Comment by SomaticIT** [comment]
Hi,

This issue has been addressed in the `v1.4.0` release which is published in npm.
You can use it now.

Thanks

**Comment by jonaskello** [comment]
@SomaticIT Thanks for taking the time to fix this :-)

**Comment by SomaticIT** [comment]
You're welcome.
Does it work for you?
